### ISSUE TITLE
Build about:preferences as a Settings app

### ISSUE THREAD

**Issue by paulrouget** [paulrouget/firefox.html#1]
Prefs should use the settings API. The UI should be displayed as an app inside the browser itself (like about:preferences in firefox)

**Comment by PalmerAL** [comment]
Settings is listed as a permission in the app manifest, but trying to use the settings API gives an error "navigator.mozSettings is undefined". What is the correct way to get this to work?

**Comment by paulrouget** [comment]
Right. I need to enable settings in the runtime.

**Comment by paulrouget** [comment]
This issue was moved to mozilla/browser.html#1
