### ISSUE TITLE
[Tabs] Add new tab button

### ISSUE THREAD

**Issue by joshua-s** [paulrouget/firefox.html#15]
It would be nice to have a "+" button to open new tabs.

![screen shot 2014-12-09 at 12 16 13 pm](https://cloud.githubusercontent.com/assets/1479244/5361963/3f6e069c-7fc7-11e4-9994-e7c87ff1ab00.png)

**Comment by paulrouget** [comment]
This issue was moved to mozilla/browser.html#5
