### ISSUE TITLE
Add scrollbox to tab bar if tabs don't fit

### ISSUE THREAD

**Issue by SebastianZ** [paulrouget/firefox.html#21]
The tab bar should add a scrollbox if the tabs don't fit into the window.
![Tab bar scrollbox](https://cloud.githubusercontent.com/assets/958943/5372192/2427172e-8045-11e4-8740-61f63a6c188d.png)

Sebastian

**Comment by paulrouget** [comment]
This issue was moved to mozilla/browser.html#8
