### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by joshua-s** [paulrouget/firefox.html#33]
Themes are an important feature in Firefox. We implemented a sample dark theme in #10, and now should refine our mechanism.

Improvements/needs:
- [ ] Switch between themes (depends on #1)
- [ ] Install 3rd-party themes
- [ ] Decide on an easier theme format
- [ ] Support lightweight themes
- [ ] Support non-firefox.html themes (is this possible?)

**Comment by paulrouget** [comment]
This issue was moved to mozilla/browser.html#12
