### ISSUE TITLE
Implement a better gecko runtime

### ISSUE THREAD

**Issue by paulrouget** [paulrouget/firefox.html#86]
We want to provide a runtime that would be able to run one or several HTML apps to implement a desktop browser. For `Firefox.html`, we use Firefox Desktop with some ugly hacks. See https://github.com/paulrouget/gecko-dev/compare/mozilla:fx-team...htmlrunner.diff

Requirements (**updated**):

- ~~user-agent style sheets need to be close to native look (not like B2G ua.css, more like Firefox's)~~
- apps can be hosted online (see with B2G team for their hosted packaged app plan + service workers (see with Vivien for patch-based updates using service-workers where he managed to update apps from github)) (requires Maple branch: https://hg.mozilla.org/projects/maple )
- support several app (browser app, settings app, processes manager app, maybe system app)
- properly integrated with the OS (make HTML app native):
  -  ~~native dialogs~~
  -  ~~native context menu~~
  -  ~~native panels~~
  -  ~~more -moz-appearance support in content~~
  -  native notifications
  -  use OS fullscreen mode if fullscreen requested
  -  native menu
  -  draw in titlebar
  -  support window dragging from content (`-moz-window-dragging`)
  -  overscroll effect
- devtools connected to apps
- standalone (maybe not Firefox Desktop or B2G. Another project? WebappRT? --enable-application=htmlrunner with its own binary name?)
- no conflict with running Firefox instances
- its own profile directory
- No XUL at all. Top level window is a HTML window
- nightly builds
- auto-update
- doesn't pollute WebRT or Firefox Desktop code

To keep the project easily hackable for now:
- no build process for apps. Auto-installation
- apps can be hosted on the disk
- super-reload (ctrl-shift-R reload all the apps, and repackage them if needed)
- command line to set location of the different apps

Sensible prefs:

- pref("browser.tabs.remote.autostart", true);
- pref("browser.chromeURL", "chrome://htmlrunner/content/shell.xul");
- pref("dom.webcomponents.enabled", true);
- pref("browser.dom.window.dump.enabled", true);
- pref("dom.mozBrowserFramesEnabled", true);
- pref("dom.ipc.processCount", 100000);
- pref("dom.webapps.useCurrentProfile", true);
- pref("security.apps.certified.CSP.default", "default-src *; script-src 'self'; object-src 'none'; style-src 'self' 'unsafe-inline' app://browser.gaiamobile.org");
- pref("network.dns.localDomains", "browser.gaiamobile.org");
- pref("devtools.webide.enableLocalRuntime", true);
- pref("htmlrunner.rootAppID", "browser.gaiamobile.org");
- pref("htmlrunner.rootAppManifest", "app://browser.gaiamobile.org/manifest.webapp");
- pref("dom.sysmsg.enabled", true);
- pref("devtools.chrome.enabled", true);
- pref("devtools.apps.forbidden-permissions", "");
- pref("devtools.debugger.forbid-certified-apps", false);
- pref("dom.datastore.enabled", true);

**Comment by Hywan** [comment]
Hello :-),

Another thing to do: `navigator.language` must be set to the locale of the OS.
